name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Launcher with Gradle
      run: ./gradlew :app:assembleDebug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Launcher-debug
        path: app/build/outputs/apk/debug/